name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wasm32-build-and-serve:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: command -v wasm-pack >/dev/null 2>&1 || cargo install --force --git https://github.com/rustwasm/wasm-pack.git --tag v0.13.1
      # https://github.com/rustwasm/wasm-bindgen/issues/4211
      - run: cargo install --force wasm-bindgen-cli --git "https://github.com/rustwasm/wasm-bindgen"
      - name: Install wasm Rust target
        run: rustup target add wasm32-unknown-unknown
      - name: Install system dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get clean && sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev libxcb-shape0-dev libxcb-xfixes0-dev libxcb1-dev
